# Generated by Django 5.1.4 on 2024-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='f_gender',
            new_name='f_Gender',
        ),
        migrations.AlterField(
            model_name='employee',
            name='f_Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
